
[Audio]
AudioVolume = 1.0
DSPEmulation = "hle"
EnableAACAudio = true
EnableAudio = false
MuteAudio = false
PrintDSPFirmware = false
VolumeCurve = "cubic"

[Battery]
BatteryPercentage = 3
ChargerPlugged = true

[GPU]
AccelerateShaders = true
AccurateShaderMultiplication = false
EnableRenderdoc = false
EnableShaderJIT = true
EnableVSync = true
ForceShadergenForLighting = true
Renderer = "opengl"
ShadergenLightThreshold = 1
UseUbershaders = true

[General]
DefaultRomPath = ""
EnableDiscordRPC = false
PrintAppVersion = true
SystemLanguage = "en"
UsePortableBuild = false

[SD]
UseVirtualSD = true
WriteProtectVirtualSD = false

[UI]
Language = "en"
Theme = "dark"
WindowIcon = "rpog"

[Window]
AppVersionOnWindow = false
RememberWindowPosition = false
WindowHeight = 480
WindowPosX = 760
WindowPosY = 300
WindowWidth = 400

