#!/usr/bin/env python3
# Bake sharp day-intro digits at the plate's real display size.

import os
import sys

import numpy as np
from PIL import Image, ImageDraw, ImageFont

ROOT = sys.argv[1] if len(sys.argv) > 1 else "."
FONT = os.path.join(ROOT, "data/fonts/149_Dokyo.ttf")
GFX = os.path.join(ROOT, "gfx")
STAGE = os.path.join(GFX, "DayNumber")
HEADER = os.path.join(ROOT, "source/Papas_DayNumber.h")

SIZE = 44  # digit ink measures 26px tall; the clip drew 23px, this reads bigger
PAD = 2  # room for the left bearing ('2' and '3' start behind the pen)

font = ImageFont.truetype(FONT, SIZE)

# Share one ink top so runtime only needs a pen and per-digit advances.
tops = {font.getbbox(d)[1] for d in "0123456789"}
bottoms = {font.getbbox(d)[3] for d in "0123456789"}
assert len(tops) == 1 and len(bottoms) == 1, (tops, bottoms)
ink_top, ink_bottom = tops.pop(), bottoms.pop()
ink_h = ink_bottom - ink_top

os.makedirs(STAGE, exist_ok=True)
advances = []
for d in "0123456789":
    bbox = font.getbbox(d)
    w = int(np.ceil(max(bbox[2], font.getlength(d)))) + 2 * PAD
    img = Image.new("L", (w, ink_h + 2 * PAD), 0)
    ImageDraw.Draw(img).text((PAD, PAD - ink_top), d, font=font, fill=255)
    alpha = np.asarray(img).astype(np.uint8)
    # White padding keeps filtering clean when the game tints the glyph.
    out = np.dstack([np.full(alpha.shape, 255, np.uint8)] * 3 + [alpha])
    Image.fromarray(out).save(f"{STAGE}/digit_{d}.png")
    advances.append(font.getlength(d))

lines = ["--atlas --border edge -f rgba -z auto", ""]
lines += [f"DayNumber/digit_{d}.png" for d in "0123456789"]
open(f"{GFX}/daynumber.t3s", "w").write("\n".join(lines) + "\n")

adv = ", ".join(f"{a:.2f}f" for a in advances)
open(HEADER, "w").write(f"""#pragma once
// Generated by tools/gen_daynumber.py; draws the baked day digits 1:1.

namespace Papas {{

\tconst int DAYNUM_INK_H = {ink_h};
\t// Each image carries this much blank space left of the pen and above the ink
\tconst float DAYNUM_PAD = {float(PAD)}f;
\tconst float DAYNUM_ADVANCE[10] = {{ {adv} }};
}}
""")
print(f"digits {SIZE}px, ink {ink_h}px tall, advances {[round(a, 2) for a in advances]}")
