#!/usr/bin/env python3
# Bake matching OPEN/CLOSED signs at their final size and tilt so they stay sharp.
#
# Usage: python3 tools/gen_sign.py [repo root]

import math
import os
import sys

import numpy as np
from PIL import Image

ROOT = sys.argv[1] if len(sys.argv) > 1 else "."
SRC = os.path.join(ROOT, "papas_extract/sprites/DefineSprite_731")
STAGE = os.path.join(ROOT, "gfx/Stations")
HEADER = os.path.join(ROOT, "source/Papas_Sign.h")

FRAMES = {"open": 1, "closed": 39}
# Match the old 46x47 art after its 1.4x runtime scale.
SCALE = 0.359 * 1.4
ANGLE = 15.0  # tilt, clockwise on screen - baked so the GPU never resamples


def load(frame):
    return np.asarray(Image.open(f"{SRC}/{frame}.png").convert("RGBA")).astype(np.float32)


def alpha_bleed(px, known, iters=8):
    """Bleed edge colours outward so filtering won't add a dark ring."""
    rgb = px[..., :3]
    known = known.copy()
    for _ in range(iters):
        if known.all():
            break
        acc = np.zeros_like(rgb)
        cnt = np.zeros(known.shape, np.float32)
        for dy in (-1, 0, 1):
            for dx in (-1, 0, 1):
                if dy == 0 and dx == 0:
                    continue
                sk = np.roll(np.roll(known, dy, 0), dx, 1)
                sr = np.roll(np.roll(rgb, dy, 0), dx, 1)
                acc += sr * sk[..., None]
                cnt += sk
        fill = (~known) & (cnt > 0)
        rgb[fill] = acc[fill] / cnt[fill, None]
        known |= fill
    return px


# One crop for both frames so the sign holds still when it flips
frames = {k: load(v) for k, v in FRAMES.items()}
op = np.zeros(next(iter(frames.values())).shape[:2], bool)
for px in frames.values():
    op |= px[..., 3] > 8
ys, xs = np.where(op)
x0, x1, y0, y1 = xs.min(), xs.max() + 1, ys.min(), ys.max() + 1

# Foot of the post: the centre of the bottom-most opaque row
bottom = np.where(op[y1 - 1])[0]
foot_src = ((bottom.min() + bottom.max() + 1) / 2.0 - x0, float(y1 - y0))
print(f"source crop {x1 - x0}x{y1 - y0}, post foot at {foot_src[0]:.1f},{foot_src[1]:.1f}")

rad = math.radians(ANGLE)
out_lines = []
for name, px in frames.items():
    cut = px[y0:y1, x0:x1].copy()

    # Premultiply so transparent texels can't colour the resampled edge.
    a = cut[..., 3:4] / 255.0
    cut[..., :3] *= a

    img = Image.fromarray(np.clip(cut, 0, 255).astype(np.uint8))
    # Rotate around the foot, accounting for PIL's opposite direction.
    pad = int(max(img.size) * 1.5)
    canvas = Image.new("RGBA", (pad * 2, pad * 2), (0, 0, 0, 0))
    canvas.paste(img, (pad - int(round(foot_src[0])), pad - int(round(foot_src[1]))))
    canvas = canvas.rotate(-ANGLE, resample=Image.BICUBIC, center=(pad, pad))

    box = canvas.getbbox()
    canvas = canvas.crop(box)
    foot = ((pad - box[0]) * SCALE, (pad - box[1]) * SCALE)

    w = max(1, int(round(canvas.width * SCALE)))
    h = max(1, int(round(canvas.height * SCALE)))
    small = np.asarray(canvas.resize((w, h), Image.LANCZOS)).astype(np.float32)

    # Back to straight alpha, then bleed for the GPU's own filtering
    al = np.clip(small[..., 3:4] / 255.0, 1e-4, None)
    small[..., :3] = np.clip(small[..., :3] / al, 0, 255)
    small = alpha_bleed(small, small[..., 3] > 8)
    Image.fromarray(np.clip(small, 0, 255).astype(np.uint8)).save(f"{STAGE}/sign_{name}.png")

    print(f"  sign_{name}: {w}x{h}, foot at {foot[0]:.1f},{foot[1]:.1f}")
    out_lines.append((name, foot, w, h))

up = {n: f for n, f, _, _ in out_lines}
open(HEADER, "w").write(f"""#pragma once
// Generated by tools/gen_sign.py; draw 1:1 from the sign-foot offsets.

namespace Papas {{

\tconst float SIGN_FOOT_OX = {up['open'][0]:.1f}f;
\tconst float SIGN_FOOT_OY = {up['open'][1]:.1f}f;
}}
""")
