#pragma once
// Generated by tools/gen_startofday.py - do not edit by hand.
// Start-of-day clip decomposition: startofday.t3x holds the background
// (index 0), the day plate with its number erased (index 1), and door/window
// patches. Coordinates are in the scaled 323x240 scene space.

namespace Papas {

	struct StartOfDayPatch {
		unsigned char srcFrame; // 1-based frame in the original clip
		unsigned char index;    // image index in startofday.t3x
		short ox, oy;
	};

	const int STARTOFDAY_SRC_FRAMES = 113;
	const float STARTOFDAY_FPS = 24.0f;
	const int STARTOFDAY_PATCH_COUNT = 53;
	const float STARTOFDAY_PLATE_X = 100.0f;
	// Centre of the erased day-number area, relative to the plate image top
	const float STARTOFDAY_DIGIT_Y = 31.2f;
	// Plate top-edge y per source frame (index 0 = frame 1)
	const float STARTOFDAY_PLATE_TRACK[STARTOFDAY_SRC_FRAMES] = {211.13f,211.13f,211.13f,211.13f,211.13f,211.13f,211.13f,211.13f,211.13f,211.13f,211.13f,211.13f,211.13f,211.13f,211.13f,211.13f,211.13f,211.13f,211.13f,211.13f,211.13f,211.13f,211.13f,211.13f,211.13f,211.13f,211.13f,211.13f,211.13f,211.13f,211.13f,210.6f,210.07f,209.53f,208.47f,206.87f,205.27f,203.13f,201.0f,198.87f,196.2f,193.0f,190.33f,186.6f,182.87f,179.13f,174.87f,170.6f,165.8f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f,161.0f};

	const StartOfDayPatch STARTOFDAY_PATCHES[STARTOFDAY_PATCH_COUNT] = {
	{ 1, 2, 23, 52 },
	{ 3, 3, 26, 52 },
	{ 5, 4, 30, 52 },
	{ 7, 5, 35, 52 },
	{ 9, 6, 41, 52 },
	{ 11, 7, 45, 51 },
	{ 13, 8, 47, 50 },
	{ 15, 9, 51, 50 },
	{ 17, 10, 55, 50 },
	{ 19, 11, 59, 50 },
	{ 21, 12, 62, 51 },
	{ 23, 13, 66, 49 },
	{ 25, 14, 69, 47 },
	{ 27, 15, 69, 46 },
	{ 29, 16, 74, 46 },
	{ 31, 17, 80, 46 },
	{ 33, 18, 95, 45 },
	{ 35, 19, 95, 47 },
	{ 37, 20, 95, 49 },
	{ 39, 21, 100, 50 },
	{ 40, 22, 100, 50 },
	{ 41, 23, 100, 50 },
	{ 42, 24, 100, 50 },
	{ 43, 25, 100, 50 },
	{ 44, 26, 100, 50 },
	{ 45, 27, 100, 50 },
	{ 46, 28, 100, 50 },
	{ 47, 29, 100, 50 },
	{ 48, 30, 100, 50 },
	{ 49, 31, 100, 50 },
	{ 50, 32, 100, 50 },
	{ 51, 33, 100, 50 },
	{ 52, 34, 100, 50 },
	{ 53, 35, 100, 50 },
	{ 54, 36, 100, 50 },
	{ 55, 37, 100, 50 },
	{ 56, 38, 100, 50 },
	{ 57, 39, 100, 50 },
	{ 58, 40, 100, 50 },
	{ 59, 41, 100, 50 },
	{ 60, 42, 100, 50 },
	{ 61, 43, 100, 50 },
	{ 62, 44, 100, 50 },
	{ 63, 45, 100, 50 },
	{ 64, 46, 100, 51 },
	{ 65, 47, 105, 51 },
	{ 66, 48, 105, 51 },
	{ 67, 49, 106, 52 },
	{ 68, 50, 106, 52 },
	{ 69, 51, 106, 52 },
	{ 70, 52, 106, 52 },
	{ 71, 53, 106, 52 },
	{ 72, 54, 106, 53 },
	};
}
