#pragma once
// Generated by tools/gen_daynumber.py; draws the baked day digits 1:1.

namespace Papas {

	const int DAYNUM_INK_H = 26;
	// Each image carries this much blank space left of the pen and above the ink
	const float DAYNUM_PAD = 2.0f;
	const float DAYNUM_ADVANCE[10] = { 27.94f, 13.11f, 24.62f, 21.83f, 25.44f, 22.27f, 24.80f, 22.56f, 22.44f, 24.80f };
}
