#pragma once
// Generated by tools/gen_newcustomer.py - do not edit by hand.
// "NEW CUSTOMER!" splash (DefineSprite_482) and its no-papa sibling
// (DefineSprite_489), decomposed for newcustomer.t3x. All coordinates are
// already in top-screen space: the 600x450 stage is scaled uniformly by
// 0.5333 and centred, so nothing needs converting at runtime.

namespace Papas {

	enum NewCustomerImage {
		NC_IMG_BG,
		NC_IMG_DISC,
		NC_IMG_SHADOW,
		NC_IMG_TITLE,
		NC_IMG_NOPAPA_BG,
		NC_IMG_SEAL,
		NC_IMG_NOPAPA_SHADOW
	};

	// Top-left corner + size an image is stretched to on a given frame; used
	// for the two morph tweens (the disc and the no-papa shadow), which are
	// reproduced by stretching their settled art through a measured box
	struct NewCustomerBox { float x, y, w, h; };
	// Top-left corner + scale of the seal on each frame of its slam-in
	struct NewCustomerSealFrame { float x, y, scale; };

	const float NEWCUSTOMER_FPS = 30.0f;
	const int NEWCUSTOMER_SRC_FRAMES = 100;
	const int NEWCUSTOMER_NOPAPA_SRC_FRAMES = 86;

	// The disc inflates for these frames and then holds its last entry
	// (a zero-width entry means it is not on stage yet)
	const int NEWCUSTOMER_DISC_FRAMES = 20;
	const NewCustomerBox NEWCUSTOMER_DISC[NEWCUSTOMER_DISC_FRAMES] = {
	{ 0.0f, 0.0f, 0.0f, 0.0f },
	{ 194.13f, 110.91f, 6.4f, 6.4f },
	{ 193.6f, 109.84f, 8.0f, 8.0f },
	{ 192.0f, 108.24f, 11.2f, 11.73f },
	{ 188.27f, 105.04f, 18.13f, 18.13f },
	{ 184.0f, 100.77f, 27.2f, 27.2f },
	{ 178.13f, 94.91f, 38.93f, 39.47f },
	{ 170.67f, 87.97f, 53.87f, 53.87f },
	{ 162.13f, 79.97f, 70.4f, 70.4f },
	{ 152.0f, 70.37f, 90.67f, 90.13f },
	{ 140.8f, 59.71f, 113.07f, 107.2f },
	{ 128.53f, 47.44f, 137.6f, 129.6f },
	{ 114.67f, 34.11f, 165.33f, 165.33f },
	{ 99.2f, 19.71f, 195.73f, 195.73f },
	{ 82.67f, 3.71f, 228.8f, 228.8f },
	{ 84.27f, 5.31f, 226.13f, 226.13f },
	{ 85.33f, 6.37f, 224.53f, 224.53f },
	{ 86.93f, 7.97f, 221.87f, 221.87f },
	{ 88.0f, 9.04f, 220.27f, 220.27f },
	{ 88.0f, 9.04f, 220.27f, 220.27f },
	};

	// Title y per frame; -1000 = not on stage yet. Holds its last entry.
	const int NEWCUSTOMER_TITLE_FRAMES = 21;
	const float NEWCUSTOMER_TITLE_X = 98.56f;
	const float NEWCUSTOMER_TITLE_Y[NEWCUSTOMER_TITLE_FRAMES] = {-1000.0f,-1000.0f,-1000.0f,-1000.0f,-1000.0f,-1000.0f,-1000.0f,-1000.0f,-1000.0f,-34.75f,-26.21f,-17.68f,-9.15f,-0.61f,7.92f,6.85f,5.79f,4.72f,5.79f,6.85f,7.92f};

	// The customer's shadow and the rig customer itself, which plays the
	// "overjoyed" segment at 80% of its Flash size
	const float NEWCUSTOMER_SHADOW_X = 162.64f;
	const float NEWCUSTOMER_SHADOW_Y = 161.07f;
	const float NEWCUSTOMER_RIG_X = 162.67f;
	const float NEWCUSTOMER_RIG_Y = 48.48f;
	const float NEWCUSTOMER_RIG_SCALE = 0.4267f;

	// Name field (DefineEditText 470: 48px, centred, black). The game font
	// isn't the original's, so the runtime scales it to this height rather
	// than to a baked-in scale factor.
	const float NEWCUSTOMER_NAME_CX = 194.12f;
	const float NEWCUSTOMER_NAME_Y = 185.23f;
	const float NEWCUSTOMER_NAME_HEIGHT = 25.6f;

	// No-papa screen: the seal slams in from offscreen over a shrinking
	// shadow. Both tracks start on source frame NEWCUSTOMER_SEAL_START and
	// hold their last entry; nothing is drawn before it.
	const int NEWCUSTOMER_SEAL_START = 16;
	const int NEWCUSTOMER_SEAL_FRAMES = 13;
	const NewCustomerSealFrame NEWCUSTOMER_SEAL[NEWCUSTOMER_SEAL_FRAMES] = {
	{ 108.21f, 22.75f, 0.9999f },
	{ 115.95f, 30.53f, 0.9166f },
	{ 123.68f, 38.35f, 0.8333f },
	{ 131.41f, 46.13f, 0.75f },
	{ 139.15f, 53.92f, 0.6668f },
	{ 146.85f, 61.71f, 0.5835f },
	{ 154.59f, 69.52f, 0.5002f },
	{ 162.32f, 77.33f, 0.4169f },
	{ 170.05f, 85.12f, 0.3336f },
	{ 169.28f, 84.35f, 0.3421f },
	{ 168.48f, 83.52f, 0.3507f },
	{ 167.71f, 82.72f, 0.3593f },
	{ 166.88f, 81.92f, 0.3679f },
	};
	const int NEWCUSTOMER_NOPAPA_SHADOW_FRAMES = 12;
	const NewCustomerBox NEWCUSTOMER_NOPAPA_SHADOW[NEWCUSTOMER_NOPAPA_SHADOW_FRAMES] = {
	{ 77.33f, 146.67f, 242.88f, 232.67f },
	{ 90.82f, 146.67f, 216.51f, 201.71f },
	{ 104.31f, 146.67f, 190.13f, 170.76f },
	{ 117.79f, 146.67f, 163.76f, 139.81f },
	{ 131.28f, 146.67f, 137.39f, 108.86f },
	{ 144.76f, 146.67f, 111.01f, 77.9f },
	{ 158.25f, 146.67f, 84.64f, 46.95f },
	{ 171.73f, 146.67f, 58.27f, 16.0f },
	{ 171.73f, 147.33f, 58.27f, 15.33f },
	{ 171.73f, 148.0f, 58.27f, 14.67f },
	{ 171.73f, 148.67f, 58.27f, 14.0f },
	{ 171.73f, 149.33f, 58.27f, 13.33f },
	};
}
