#pragma once
// Generated by tools/gen_giveorder.py; cropped half-size frames of Roy's clip.

namespace Papas {

	struct GiveOrderFrame {
		unsigned char srcFrame; // 1-based frame in the original clip
		unsigned char sheet;    // giveorder_roy<sheet+1>.t3x
		unsigned char index;    // image index within that sheet
		short ox, oy;
	};

	const int GIVEORDER_SHEET_COUNT = 5;
	const int GIVEORDER_FRAME_COUNT = 37;
	const int GIVEORDER_SRC_FRAMES = 94;
	const float GIVEORDER_FPS = 24.0f;

	const GiveOrderFrame GIVEORDER_FRAMES[GIVEORDER_FRAME_COUNT] = {
	{ 37, 0, 0, 62, 28 },
	{ 46, 0, 1, 62, 27 },
	{ 47, 0, 2, 61, 26 },
	{ 48, 0, 3, 61, 26 },
	{ 49, 0, 4, 60, 26 },
	{ 50, 0, 5, 60, 26 },
	{ 51, 0, 6, 60, 23 },
	{ 52, 0, 7, 60, 12 },
	{ 53, 1, 0, 60, 0 },
	{ 54, 1, 1, 60, 0 },
	{ 55, 1, 2, 60, 0 },
	{ 56, 1, 3, 60, 0 },
	{ 57, 1, 4, 60, 0 },
	{ 58, 1, 5, 58, 0 },
	{ 59, 1, 6, 58, 0 },
	{ 60, 1, 7, 56, 0 },
	{ 61, 2, 0, 56, 0 },
	{ 62, 2, 1, 54, 0 },
	{ 63, 2, 2, 54, 0 },
	{ 64, 2, 3, 52, 0 },
	{ 65, 2, 4, 52, 0 },
	{ 66, 2, 5, 50, 0 },
	{ 67, 2, 6, 50, 0 },
	{ 68, 3, 0, 50, 0 },
	{ 70, 3, 1, 49, 0 },
	{ 72, 3, 2, 48, 0 },
	{ 74, 3, 3, 48, 0 },
	{ 76, 3, 4, 48, 0 },
	{ 78, 3, 5, 48, 0 },
	{ 80, 3, 6, 66, 0 },
	{ 82, 3, 7, 82, 0 },
	{ 84, 4, 0, 84, 0 },
	{ 86, 4, 1, 84, 0 },
	{ 88, 4, 2, 68, 0 },
	{ 90, 4, 3, 62, 0 },
	{ 92, 4, 4, 66, 0 },
	{ 94, 4, 5, 70, 0 },
	};
}
